### ISSUE TITLE
USB 连接时，电脑连接上 shell 有的电脑需要好几次才能连接上。

### ISSUE THREAD

**Issue by SummerGift** [heyuanjie87/adbd#13]
如题。

**Comment by SummerGift** [comment]
在出现问题的电脑上进行多次测试，有时会出现下面的错误：
```
Command failed: c:\Users\rtt\Desktop\company3\vscode_micropython\adb\adb.exe devices
error: protocol fault (couldn't read status): Connection reset by peer
```

我们这边能保证每次进行 adb shell 之前，使用 adb device 时都能获得 adb 设备，但是此时使用 adb shell 连接则可能失败。

错误失败提示如下：
```
error : closed
```
一般情况下再尝试几次就就可以连接成功，也有一直失败的情况。

现在如下疑问：

- 什么情况下可以进行 shell 连接？
- shell 连接是否需要手动断开才能保证下次连接正确进行？

**Comment by heyuanjie87** [comment]
电脑中安装了“电脑管家”之类的软件一直在调用shell,而rtt中shell只能打开一个导致需要多次重试
