### ISSUE TITLE
【RT-Thread】adb功能咨询 

### ISSUE THREAD

**Issue by Devilliv** [heyuanjie87/adbd#15]
请问当前该项目是已经支持usb adb功能了吗？需要如何集成到RT-Thread的SDK上？
另，请问您在什么开发板上测试过？我也想买一块来学习下，谢谢！

**Comment by heyuanjie87** [comment]
这个在x1000,imxrt1052,iotboard上都测试过usb,就学习而言你可以选正点原子的 潘多拉iotboard价格实惠

**Comment by Devilliv** [comment]
谢谢解答
