### ISSUE TITLE
如果想将 adbd 在 Linux 下运行该如何处理呢？

### ISSUE THREAD

**Issue by taotieren** [heyuanjie87/adbd#20]
目前我用的是 Arch Linux 系统。想将其打包到 [AUR 仓库](https://aur.archlinux.org/)

**Comment by heyuanjie87** [comment]
我这个只能在rtthread中使用，要在linux中用你可以从android项目中提取相关代码。

**Comment by heyuanjie87** [comment]
我这个只能在rtthread中使用，要在linux中用你可以从android项目中提取相关代码。
