### ISSUE TITLE
tcp transport 模式下经常报错

### ISSUE THREAD

**Issue by tomyqg** [heyuanjie87/adbd#23]
请教下push文件夹经常报如下错误，该如何排查问题
[E/ADB sync] fail - filename read failure
[E/ADB] service enqueue failed

 @另外请问下有支持cherryusb的计划吗？

**Comment by heyuanjie87** [comment]
我看cherryusb作者用rndis和tcp模式跑起来adb的。
我比较怀疑你的tcp通信有问题，过两周我试试tcp看看有没问题

**Comment by tomyqg** [comment]
我也是用的cherryusb的rndis从机网卡和tcp跑的adb,应该是在他之前就跑起来的吧

**Comment by heyuanjie87** [comment]
弄了个有网卡的板子试了下确实跑不起来了，我抽点时间找下问题
