### ISSUE TITLE
adb shell 使用 exitas 断开后设备端没有恢复。

### ISSUE THREAD

**Issue by SummerGift** [heyuanjie87/adbd#9]
在 W60X 开发板上测试，连接上 adb shell 之后使用 exitas  命令断开，设备端 shell 无法恢复，此时如果再次在 PC 端使用 adb shell 进行连接，就会进入断言。

`
(obj != object) assertion failed at function:rt_object_init, line number:265
`

**Comment by heyuanjie87** [comment]
已经找到了问题，是有一处与我原版不符引起，等我咨询下提交者的改动原因再修复
